name: Build and Release Electron App

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        platform:
          - win
          - linux
          - mac
        include:
          - platform: mac
            runs-on: macos-latest
          - platform: win
            runs-on: windows-latest
          - platform: linux
            runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install dmg-license for mac
        if: matrix.platform == 'mac'
        run: |
          pnpm i -D dmg-license

      - name: Build and package app for ${{ matrix.platform }}
        run: pnpm run build:${{ matrix.platform }}

      - name: Upload dist to Artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          name: dist-${{ matrix.platform }}
          path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: dist-*
          path: dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          tag: v1.0.1
          body: |
            Release ${{ github.ref }}
